(() => {
  "use strict";
  const core=window.IPASProgressCore,body=document.body,nodes=[...document.querySelectorAll(".learning-unit")];
  const units=nodes.sort((a,b)=>Number(a.dataset.order)-Number(b.dataset.order)).map(node=>({id:node.id,subject:node.dataset.subject,order:Number(node.dataset.order),title:node.dataset.title,topic:node.dataset.topic,node,dates:JSON.parse(node.dataset.scheduleDates),search:node.textContent.toLocaleLowerCase("zh-Hant")}));
  const ids = units.map((unit) => unit.id);
  const catalog=Object.fromEntries(units.map(u=>[u.id,[...u.node.querySelectorAll(".recall-question")].map(n=>n.dataset.promptId)]));
  const links=new Map([...document.querySelectorAll("a[data-target]")].map(a=>[a.dataset.target,a]));
  const $=id=>document.getElementById(id),text=(id,value)=>{$(id).textContent=value;},html=value=>{const n=document.createElement("span");n.textContent=value;return n.innerHTML;};
  const testDates=new URL(location.href).searchParams.getAll("test_date");
  const testDate=testDates.length===1&&core.validDate(testDates[0])?testDates[0]:null;
  const today=()=>testDate||core.localDate(),now=()=>testDate?new Date(testDate+"T12:00:00"):new Date();
  let state=core.blank(ids),currentId=ids[0],filter="all",storageFailed=false;
  const storageError=document.createElement("p");storageError.id="storage-error";storageError.className="storage-error";storageError.setAttribute("role","alert");storageError.hidden=true;$("progress-live").before(storageError);
  function announce(message,error=false){text("progress-live",message);$("progress-live").classList.toggle("is-error",error);}
  function storageFailure(error){storageFailed=true;storageError.hidden=false;storageError.textContent=`本機儲存失敗：${error.message}。目前操作仍保留在記憶體；請立即匯出，關閉或重新整理會失去未儲存資料。`;}
  function persist(){try{localStorage.setItem(core.KEY,JSON.stringify(core.exportPayload(state)));if(storageFailed){storageFailed=false;storageError.hidden=true;}}catch(error){storageFailure(error);}}
  try{const saved=localStorage.getItem(core.KEY),legacy=saved?null:localStorage.getItem(core.LEGACY_KEY);state=core.hydrate(JSON.parse(saved||legacy||"null"),ids,catalog);if(legacy){persist();announce("v1 已遷移為 v2，完成日期與舊備份保留。");}}catch(error){storageFailure(error);}
  text("storage-origin",location.protocol==="file:"?`file:// · ${location.pathname}`:location.origin);
  const dialog=$("action-dialog");
  function ask(title,message,information=false){return new Promise(resolve=>{const previous=document.activeElement;text("dialog-title",title);text("dialog-message",message);$("dialog-cancel").hidden=information;$("dialog-ok").textContent=information?"知道了":"確認";let settled=false;function finish(ok){if(settled)return;settled=true;dialog.close();$("dialog-ok").removeEventListener("click",yes);$("dialog-cancel").removeEventListener("click",no);dialog.removeEventListener("cancel",escape);if(previous?.isConnected)previous.focus();resolve(ok);}const yes=()=>finish(true),no=()=>finish(false),escape=e=>{e.preventDefault();finish(false);};$("dialog-ok").addEventListener("click",yes);$("dialog-cancel").addEventListener("click",no);dialog.addEventListener("cancel",escape);dialog.showModal();(information?$("dialog-ok"):$("dialog-cancel")).focus();});}
  function setCurrent(id){if(!links.has(id))return;currentId=id;links.forEach((a,key)=>a.classList.toggle("is-active",key===id));text("reading-position",`閱讀位置：Order ${units.find(u=>u.id===id).order}`);}
  const panel=$("toc-panel"),backdrop=$("toc-backdrop"),menuButton=$("menu-button"),mobile=matchMedia("(max-width: 900px)");
  function syncDrawer(){const open=mobile.matches&&panel.classList.contains("is-open");panel.inert=mobile.matches&&!open;panel.setAttribute("aria-hidden",String(panel.inert));$("reader-content").inert=open;body.classList.toggle("menu-open",open);menuButton.setAttribute("aria-expanded",String(open));menuButton.setAttribute("aria-label",open?"關閉 LU 目錄":"開啟 LU 目錄");backdrop.hidden=!open;}
  function closeMenu(){const was=panel.classList.contains("is-open");panel.classList.remove("is-open");syncDrawer();if(was&&mobile.matches)menuButton.focus({preventScroll:true});}
  function jump(id){const target=$(id);if(!target)return;setCurrent(id);closeMenu();target.scrollIntoView({behavior:"smooth",block:"start"});}
  menuButton.addEventListener("click",()=>{if(panel.classList.contains("is-open"))closeMenu();else{panel.classList.add("is-open");syncDrawer();$("toc-close").focus();}});
  mobile.addEventListener("change",()=>{panel.classList.remove("is-open");syncDrawer();});$("toc-close").addEventListener("click",closeMenu);backdrop.addEventListener("click",closeMenu);
  document.addEventListener("keydown",event=>{if(dialog.open)return;if(event.key==="Escape")closeMenu();if(event.key==="Tab"&&mobile.matches&&panel.classList.contains("is-open")){const focusable=[...panel.querySelectorAll("a,button,input")].filter(n=>!n.disabled&&!n.closest("[hidden]")&&n.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  document.querySelector("[data-guide-link]").addEventListener("click",closeMenu);syncDrawer();
  const pct=(n,total)=>Math.round(n/total*1000)/10,bar=(id,value)=>{$(id).style.width=`${value}%`;},dateText=d=>d.replaceAll("-","/");
  const unitLink=u=>`<a href="#${u.id}" data-jump="${u.id}">Order ${u.order} ${html(u.title)}</a>`;
  function render(){
    const summary=core.stats(state,units,today()),next=core.nextId(state,ids),current=units.find(u=>u.id===next),overall=pct(summary.completed,64);
    text("overall-count",`${summary.completed} / 64 LU`);text("overall-percent",`${overall}%`);bar("overall-bar",overall);text("side-progress-count",`${summary.completed} / 64`);bar("side-progress-bar",overall);text("mobile-progress",`${summary.completed} / 64`);
    for(const subject of ["Z02-01","Z02-03"]){const v=summary.subjects[subject];bar(`bar-${subject}`,pct(v.completed,v.total));text(`count-${subject}`,`${v.completed} / ${v.total}`);}
    text("today-date",dateText(today()));text("today-count",`今日完成 ${summary.today.length} 個 LU`);$("today-list").innerHTML=summary.today.map(u=>`<li>✓ ${unitLink(u)}</li>`).join("");
    text("current-order",current?`Order ${current.order}`:"Order 1–64");text("side-current-order",current?`Order ${current.order}`:"第一輪完成");text("current-id",current?current.id:"64 / 64");text("current-title",current?current.title:"第一輪學習已完成");text("mobile-current",current?`Order ${current.order}`:"已完成");
    document.querySelectorAll("[data-continue]").forEach(b=>{b.disabled=!current;b.dataset.target=next||"";});
    for(const unit of units){const record = state[unit.id],done=record.status==="COMPLETED",link=links.get(unit.id),date=done?dateText(record.completed_at.date):"",rated=catalog[unit.id].filter(id=>record.recall[id]).length,total=catalog[unit.id].length;
      unit.node.dataset.progressStatus=record.status;unit.node.querySelector(".unit-progress-state").textContent=done?"✓ 已完成":record.status==="IN_PROGRESS"?"◐ 學習中":"○ 尚未完成";unit.node.querySelector(".unit-progress-date").textContent=date;
      const complete=unit.node.querySelector(".complete-button");complete.hidden=done;complete.disabled=rated!==total;complete.textContent=`完成本 LU（已自評 ${rated} / ${total}）`;unit.node.querySelector(".rating-count").textContent=`已自評 ${rated} / ${total}`;unit.node.querySelector(".skip-recall").hidden=done;unit.node.querySelector(".cancel-button").hidden=!done;
      unit.node.querySelectorAll("[data-rating]").forEach(r=>{r.checked=record.recall[r.dataset.prompt]?.rating===r.value;});link.querySelector(".toc-state").textContent=done?"✓":record.status==="IN_PROGRESS"?"◐":"○";link.querySelector(".toc-date").textContent=date;link.title=done?`已完成：${date}`:record.status;link.closest("li").hidden=filter==="completed"?!done:filter==="incomplete"?done:false;
    }
    const hints=core.scheduleHints(state,units,today());text("schedule-date",dateText(today()));$("schedule-today").innerHTML=hints.today.map(u=>`<li>${state[u.id].status==="COMPLETED"?"✓ ":""}${unitLink(u)}</li>`).join("")||"<li>今日沒有指定 LU。</li>";text("schedule-overdue",`已逾期未完成 ${hints.overdue} 個 LU`);text("schedule-remaining",`距 2026-10-31 剩 ${hints.days} 天 · 未完成 ${hints.remaining} 個 LU`);
    $("needs-review").innerHTML=core.needsReview(state).map(id=>`<li>${unitLink(units.find(u=>u.id===id))}</li>`).join("")||"<li>目前沒有部分或答錯的自評。</li>";setCurrent(currentId);runSearch();
  }
  document.addEventListener("click",async event=>{
    const reveal=event.target.closest(".reveal-answer,.reveal-scenario"),complete=event.target.closest(".complete-button"),skip=event.target.closest(".skip-recall"),cancel=event.target.closest(".cancel-button"),link=event.target.closest("[data-jump],[data-continue],a[data-target]");
    if(reveal){const open=reveal.getAttribute("aria-expanded")!=="true";reveal.setAttribute("aria-expanded",String(open));$(reveal.getAttribute("aria-controls")).hidden=!open;reveal.textContent=open?(reveal.classList.contains("reveal-scenario")?"隱藏解析":"隱藏參考答案"):(reveal.classList.contains("reveal-scenario")?"顯示解析":"顯示參考答案");if(open){state=core.inProgress(state,reveal.dataset.id);persist();render();}}
    if(complete&&!complete.disabled){state=core.complete(state,complete.dataset.id,now());persist();render();announce("已記錄完成日期。");complete.closest("article").querySelector(".cancel-button").focus();}
    if(skip&&await ask("略過 Recall 並完成","此次尚未完成的自評將略過，紀錄會標示 skipped_recall。確認完成本 LU？")){state=core.complete(state,skip.dataset.id,now(),true);persist();render();announce("已完成並記錄略過自評。");skip.closest("article").querySelector(".cancel-button").focus();}
    if(cancel&&await ask("取消完成","保留自評，取消這個 LU 的完成日期？")){state=core.cancel(state,cancel.dataset.id);persist();render();announce("已取消完成紀錄。");cancel.closest("article").querySelector(".skip-recall").focus();}
    if(link&&(link.dataset.target||link.dataset.jump)){event.preventDefault();jump(link.dataset.target||link.dataset.jump);}
  });
  document.addEventListener("change",event=>{const r=event.target.closest("[data-rating]");if(r){state=core.rate(state,r.dataset.id,r.dataset.prompt,r.value,now());persist();render();announce("已記錄自評。");}});
  const search=$("lu-search");let timer;search.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(runSearch,180);});
  function runSearch(){const query=search.value.trim().toLocaleLowerCase("zh-Hant"),result=$("search-results");if(!query){result.hidden=true;result.innerHTML="";return;}const matches=units.filter(u=>u.search.includes(query)&&(filter==="all"||(filter==="completed")===(state[u.id].status==="COMPLETED")));result.hidden=false;result.innerHTML=`<strong>搜尋結果 ${matches.length}</strong>`+matches.slice(0,30).map(u=>`<div>${unitLink(u)}</div>`).join("")+(matches.length?"":"<p>沒有符合的 Learning Unit。</p>");}
  document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{filter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("is-selected",b===button));render();}));
  $("export-progress").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(core.exportPayload(state),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`ipas-learning-progress-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
  const importer=$("import-file");$("import-progress").addEventListener("click",()=>importer.click());importer.addEventListener("change",async()=>{if(!importer.files[0])return;try{const payload=JSON.parse(await importer.files[0].text()),merged=core.merge(state,payload,ids,catalog);state=merged;persist();render();announce("匯入完成；完成日期與自評依時間合併。");}catch(error){announce(`匯入失敗：${error.message}`,true);await ask("匯入失敗",`${error.message} 目前進度未變更。`,true);}finally{importer.value="";}});
  $("reset-progress").addEventListener("click",async()=>{if(!await ask("重設學習進度","這會清除完成日期與自評；建議先匯出。是否繼續？"))return;if(!await ask("再次確認","確定重設全部 64 個 LU 的學習紀錄？"))return;state=core.blank(ids);persist();try{localStorage.removeItem(core.LEGACY_KEY);}catch(error){storageFailure(error);}document.querySelectorAll(".answer-panel,.scenario-answer").forEach(n=>n.hidden=true);document.querySelectorAll(".reveal-answer,.reveal-scenario").forEach(n=>{n.setAttribute("aria-expanded","false");n.textContent=n.classList.contains("reveal-scenario")?"顯示解析":"顯示參考答案";});render();announce("學習進度已重設。");});
  const top=$("back-to-top");window.addEventListener("scroll",()=>top.classList.toggle("is-visible",scrollY>640),{passive:true});top.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
  const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(visible[0])setCurrent(visible[0].target.id);},{rootMargin:"-20% 0px -72% 0px"});units.forEach(u=>observer.observe(u.node));render();
})();
